- name: Rebooting {{ hosts }}
  hosts: '{{ hosts }}'
  become: true
  gather_facts: false
  serial: 2
  tasks:
    - name: Reboot the server and wait for it to come back up.
      shell: "sleep 5 && shutdown -r now"
      async: 1
      poll: 0
    - name: Wait for the reboot to complete if there was a change.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
