- name: Upgrading Packages on {{ hosts }}
  hosts: '{{ hosts }}'
  become: true
  serial: 2
  tasks:
    - name: Update APT packages
      apt:
        update_cache: yes
        upgrade: dist
      register: update_result  
    - name: Reboot the server and wait for it to come back up.
      shell: "sleep 5 && shutdown -r now"
      async: 1
      poll: 0
      when: update_result is changed
    - name: Wait for the reboot to complete if there was a change.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      when: task_result is changed
