- name: Add Kubernetes repository key
  apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add Kubernetes repository to /etc/apt/sources.list.d/kubernetes.list
  apt_repository:
          repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
          filename: kubernetes
          state: present

- name: Update packages
  apt:
          update_cache: yes
          upgrade: yes

- name: Install Weave Net as Container Network Interface
  get_url:
    url: git.io/weave
    dest: /usr/local/bin/weave
    mode: 0755

- name: Install kubernetes
  apt:
    name: "{{ item }}"
    force: yes
    state: present
  with_items:
          kubeadm

- name: Install nfs-common
  apt:
    name: nfs-common
    state: present