- replace:
    path: /boot/cmdline.txt
    regexp: 'cgroup_memory=1$'
    replace: 'cgroup_memory=1 cgroup_cpuset=1'

- name: Ensure hostname set to {{ inventory_hostname }}
  hostname:
          name: "{{ inventory_hostname }}"
  when: not inventory_hostname|match('(\d{1,3}\.){3}\d{1,3}')

- name: Change entry in /etc/hosts
  lineinfile:
           dest: /etc/hosts
           regexp: '^127\.0\.1\.1[ \t](.*)'
           line: '127.0.1.1 {{ inventory_hostname }}'
           state: present

- name: Ensure hostname is in /etc/hosts
  lineinfile:
           dest: /etc/hosts
           regexp: "^{{ ansible_default_ipv4.address }}.+$"
           line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"

- name: Restart hostname
  shell: "hostnamectl set-hostname {{ inventory_hostname }}"

- name: Load Kernel Modules
  shell: "modprobe ip_vs_wrr ip_vs_sh ip_vs ip_vs_rr"

- name: Change entry in /etc/hosts
  lineinfile:
           dest: /etc/hosts
           regexp: '^127\.0\.1\.1[ \t](.*)'
           line: '127.0.1.1 {{ inventory_hostname }}'
           state: present